### ISSUE TITLE
请问一下Ubuntu具体怎么配，已经本地部署了UNM

### ISSUE THREAD

**Issue by 1048632280** [FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM#1]
![image](https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM/assets/49977354/02155d98-f20f-44d6-99e5-326d6e6f293f)
显示运行成功，把这段url填入了ini文件中的unm_address。
然后是环境变量
![image](https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM/assets/49977354/c9579478-755b-42d4-9814-b9788269e3a3)
显示也是成功的
![image](https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM/assets/49977354/0cf79fe8-9349-4156-a202-d5b25a630fe9)

应该是都配好了，还是不能播放无版权歌曲

**Comment by 1048632280** [comment]
我尝试在win客户端连接代理成功了，可以听无版权，unm.service里面也有解析记录。
但是在ts端下达指令后，并没有调用unm服务去解析，unm的address我也改过，但是都不起作用

**Comment by Sukiyouz** [comment]
我也有同样的问题 请问你解决了吗

**Comment by FiveHair** [comment]
版权音乐的版本需要自己编译

**Comment by FiveHair** [comment]
@Sukiyouz @1048632280 目前只支持’!yun play 歌曲名称 歌手‘ 
[YunPlugin-UNM.zip](https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM/files/13753572/YunPlugin-UNM.zip)

**Comment by 1048632280** [comment]
> 目前只支持'！yun play 歌曲名称 歌手' [YunPlugin-UNM.zip](https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM/files/13753572/YunPlugin-UNM.zip)

不好意思现在才回复，我用了这个新的插件，在ts中按照格式发送后，返回502错误。
![image](https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM/assets/49977354/bd804ce1-b257-489d-a3d0-11816db80b6a)

在linux服务中查看网易云api日志，发现可能是代理问题。
![image](https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM/assets/49977354/b088966f-016f-4dce-87f1-24abdec056f5)

但是我用网易云win端可以使用这个代理成功解锁无版权音乐

**Comment by FiveHair** [comment]
> > 目前只支持'！yun play 歌曲名称 歌手' [YunPlugin-UNM.zip](https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM/files/13753572/YunPlugin-UNM.zip)
> 
> 不好意思现在才回复，我用了这个新的插件，在ts中按照格式发送后，返回502错误。 ![image](https://private-user-images.githubusercontent.com/49977354/294089571-bd804ce1-b257-489d-a3d0-11816db80b6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNTQ1MzQsIm5iZiI6MTcwNDM1NDIzNCwicGF0aCI6Ii80OTk3NzM1NC8yOTQwODk1NzEtYmQ4MDRjZTEtYjI1Ny00ODlkLWEzZDAtMTE4MTZkYjgwYjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDA3NDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NjQ3MjRlODQ5OTcyODEwYWUxYTk2ZjMzZjI5YjhjNDMzNGRmODBmNDczYWJiZGVmNTJhNzAyMTk3NDkwNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yimH6yqT6-jA_t_fEZkGw_JgNur3NNsswOpZLo7l6nk)
> 
> 在linux服务中查看网易云api日志，发现可能是代理问题。 ![image](https://private-user-images.githubusercontent.com/49977354/294089675-b088966f-016f-4dce-87f1-24abdec056f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNTQ1MzQsIm5iZiI6MTcwNDM1NDIzNCwicGF0aCI6Ii80OTk3NzM1NC8yOTQwODk2NzUtYjA4ODk2NmYtMDE2Zi00ZGNlLTg3ZjEtMjRhYmRlYzA1NmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDA3NDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMDI4YmE1YjQ0OTEwODM3ZGI1OGZlMGRkNjA5NGFkODgzMzRiNzE4YWYyZDM2YzgwZTBhZDQ4MjdiZjc5YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.meQ_jyNPUfRqoDTCjK1MlG66wYCJyPmsIKXxCpr9P44)
> 
> 但是我用网易云win端可以使用这个代理成功解锁无版权音乐


需要在自建的 [NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi)（推荐Docker版）里面的 app.js 中添加 process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = 0, 如果是docker版的话就在环境里面添加NODE_TLS_REJECT_UNAUTHORIZED = 0。

这个你添加了吗

**Comment by 1048632280** [comment]
> > > 目前只支持'！yun play 歌曲名称 歌手' [YunPlugin-UNM.zip](https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM/files/13753572/YunPlugin-UNM.zip)
> > 
> > 
> > 不好意思现在才回复，我用了这个新的插件，在ts中按照格式发送后，返回502错误。![image](https://private-user-images.githubusercontent.com/49977354/294089571-bd804ce1-b257-489d-a3d0-11816db80b6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNTQ1MzQsIm5iZiI6MTcwNDM1NDIzNCwicGF0aCI6Ii80OTk3NzM1NC8yOTQwODk1NzEtYmQ4MDRjZTEtYjI1Ny00ODlkLWEzZDAtMTE4MTZkYjgwYjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDA3NDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NjQ3MjRlODQ5OTcyODEwYWUxYTk2ZjMzZjI5YjhjNDMzNGRmODBmNDczYWJiZGVmNTJhNzAyMTk3NDkwNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yimH6yqT6-jA_t_fEZkGw_JgNur3NNsswOpZLo7l6nk)
> > 在linux服务中查看网易云api日志，发现可能是代理问题。![image](https://private-user-images.githubusercontent.com/49977354/294089675-b088966f-016f-4dce-87f1-24abdec056f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNTQ1MzQsIm5iZiI6MTcwNDM1NDIzNCwicGF0aCI6Ii80OTk3NzM1NC8yOTQwODk2NzUtYjA4ODk2NmYtMDE2Zi00ZGNlLTg3ZjEtMjRhYmRlYzA1NmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDA3NDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMDI4YmE1YjQ0OTEwODM3ZGI1OGZlMGRkNjA5NGFkODgzMzRiNzE4YWYyZDM2YzgwZTBhZDQ4MjdiZjc5YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.meQ_jyNPUfRqoDTCjK1MlG66wYCJyPmsIKXxCpr9P44)
> > 但是我用网易云win端可以使用这个代理成功解锁无版权音乐
> 
> 需要在自建的 [NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi)（推荐Docker版）里面的 app.js 中添加 process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = 0， 如果是docker版的话就在环境里面添加NODE_TLS_REJECT_UNAUTHORIZED = 0。
> 
> 这个你添加了吗

添加了，我不是docker的所以直接在app.js中修改
![image](https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM/assets/49977354/fefe8938-8a13-4c18-b6fc-2286373e2c73)

运行网易云api服务也显示
![image](https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM/assets/49977354/2fd8f4d0-d563-4c01-8a3f-1be08427c1bd)

**Comment by FiveHair** [comment]
@1048632280  这个报错应该是网易云api和UnblockNeteaseMusic的问题，UNM只是调用网易云api，并不参与它们之间的通讯。有环境的话试一试docker版本的网易云api和UnblockNeteaseMusic吧。

**Comment by 1048632280** [comment]
> @1048632280  这个报错应该是网易云api和UnblockNeteaseMusic的问题，UNM只是调用网易云api，并不参与它们之间的通讯。有环境的话试一试docker版本的网易云api和UnblockNeteaseMusic吧。

好的好的，谢谢解答
