### ISSUE TITLE
加载歌单列表时报错

### ISSUE THREAD

**Issue by MIKU-N** [FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM#10]
在加载歌单列表时，本应正常加载的列表突然返回错误
```
ts3audiobot  | 
ts3audiobot  | 18:42:56.1840| INFO|Api| ::ffff:45.66.***.*** Requested: /api/bot/use/0/(/json/merge/(/server/tree)/(/whisper/list))
ts3audiobot  | 18:42:56.8029| INFO|0| User Rain requested: !yun gedanid 643854422
ts3audiobot  | 查询循环次数0
ts3audiobot  | 1308782023
ts3audiobot  | 1338490248
ts3audiobot  | 1383205688
ts3audiobot  | 1824020871
ts3audiobot  | 29019227
ts3audiobot  | 550936829
ts3audiobot  | 1984758339
ts3audiobot  | 1303019637
ts3audiobot  | 438981332
ts3audiobot  | 442869301
ts3audiobot  | 4172700
ts3audiobot  | 1457698674
ts3audiobot  | 2070351310
ts3audiobot  | 1931176549
ts3audiobot  | 1368754688
ts3audiobot  | 1497588709
ts3audiobot  | 1890494798
ts3audiobot  | 1340890767
ts3audiobot  | 1960362416
ts3audiobot  | 4386589
ts3audiobot  | 1983593233
ts3audiobot  | 545947135
ts3audiobot  | 1981224611
ts3audiobot  | 1345485069
ts3audiobot  | 16957780
ts3audiobot  | 472045266
ts3audiobot  | 1329665666
ts3audiobot  | 4899152
ts3audiobot  | 1496086504
ts3audiobot  | 1496089152
ts3audiobot  | 1979375472
ts3audiobot  | 1831854571
ts3audiobot  | 28535356
ts3audiobot  | 1500151581
ts3audiobot  | 1396151812
ts3audiobot  | 1409311773
ts3audiobot  | 1804292550
ts3audiobot  | 1382838382
ts3audiobot  | 1411973459
ts3audiobot  | 33933853
ts3audiobot  | 26625301
ts3audiobot  | 1859245776
ts3audiobot  | 1448162422
ts3audiobot  | 1492283139
ts3audiobot  | 1817410059
ts3audiobot  | 1499313762
ts3audiobot  | 33933850
ts3audiobot  | 28263184
ts3audiobot  | 1346907833
ts3audiobot  | 18:42:58.6636|ERROR|0| Unexpected command error: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
```
使用本项目V1.1版本时出现

在使用原先的老版本UNM项目时正常播放
https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/releases/tag/2.0.3

服务器环境使用Docker自行编译的ARM版本，使用的DockerFile文件如下
```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine-arm64v8

# which version and flavour of the audiobot to use
ARG TS3_AUDIOBOT_RELEASE="0.12.0"
ARG TS3_AUDIOBOT_FLAVOUR="TS3AudioBot_dotnetcore3.1.zip"

# user id
ARG PUID=9999
ENV USER ts3bot

# install all pre-requisites, these will be needed always
RUN apk add \
    opus-dev \
    youtube-dl \
    ffmpeg

# download and install the TS3AudioBot in the specified version and flavour
RUN mkdir -p /app \
    && cd /app \
    && echo "downloading https://github.com/Splamy/TS3AudioBot/releases/download/${TS3_AUDIOBOT_RELEASE}/${TS3_AUDIOBOT_FLAVOUR}" \
    && wget https://github.com/Splamy/TS3AudioBot/releases/download/${TS3_AUDIOBOT_RELEASE}/${TS3_AUDIOBOT_FLAVOUR} -O TS3AudioBot.zip \
    && unzip TS3AudioBot.zip \
    && rm TS3AudioBot.zip

# add user to run under
RUN adduser --disabled-password -u "${PUID}" "${USER}"

# make data directory and chown it to the ts3bot user
RUN mkdir -p /app/data
RUN chown -R "${USER}" /app/data

# set user to ts3bot, we dont want to be root from now on
USER "${USER}"

# set the work dir to data, so users can properly mount their config files to this dir with -v /host/path/to/data:/data
WORKDIR /app/data

# expose the webserver port
EXPOSE 58913

CMD ["dotnet", "/app/TS3AudioBot.dll", "--non-interactive"]

```
```
docker build -f Dockerfile -t local.docker.image/ts3audiobot:latest .
```
Docker-Composer文件如下
```
version: '3'

services:
  ts3audiobot:
    image: local.docker.image/ts3audiobot
    container_name: ts3audiobot
    restart: always
    ports:
      - 58913:58913
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /home/TS3AB:/app/data
```

**Comment by FiveHair** [comment]
您好，我这里!yun gedanid 643854422没有复现。
![image](https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM/assets/16514929/bc6630ea-1d05-4746-878f-de15c37aea9b)

**Comment by MIKU-N** [comment]
> 您好，我这里!yun gedanid 643854422没有复现。 ![image](https://private-user-images.githubusercontent.com/16514929/316704028-bc6630ea-1d05-4746-878f-de15c37aea9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MTkzODEsIm5iZiI6MTcxMTQxOTA4MSwicGF0aCI6Ii8xNjUxNDkyOS8zMTY3MDQwMjgtYmM2NjMwZWEtMWQwNS00NzQ2LTg3OGYtZGUxNWMzN2FlYTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDAyMTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxMmQ4OTE5MTJjNzUzYWMyYTM0YWY3MjdiMWM1NjcyZDg5ZTMyZjJhNDcwMTUxM2FiZWE0M2M0MTQzYWFkZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zB_eY7kufgdDm8q5ri9Fy9FlxvM8lJKCNt0T8Blnu9Q)

感谢回复
目前怀疑到是海外IP拿到的json有问题，我正在做realIP参数的增加，晚些时候再回复你

**Comment by MIKU-N** [comment]
> 您好，我这里!yun gedanid 643854422没有复现。 ![image](https://private-user-images.githubusercontent.com/16514929/316704028-bc6630ea-1d05-4746-878f-de15c37aea9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0Mzk5MzgsIm5iZiI6MTcxMTQzOTYzOCwicGF0aCI6Ii8xNjUxNDkyOS8zMTY3MDQwMjgtYmM2NjMwZWEtMWQwNS00NzQ2LTg3OGYtZGUxNWMzN2FlYTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA3NTM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZjQyYzE2YTk2NWNmNmE4OGMzMTQ1ZDBlMTRiNDI1YTJiZmYzODI1NmJiMGZhNzA1YWM2MTMzOTg0MjI3OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RomTjAKx_6KaWuG_jURC0ViujPJITIROyALe1SJm7uU)

现在我确定是网易云那边的幺蛾子，海外IP存在查询错误/歌单列表结果异常的问题，在我这里增加RealIP参数后程序正常了。

**Comment by MIKU-N** [comment]
具体可以使用我修改后的版本测试
 https://github.com/MIKU-N/TS3AudioBot-NetEaseCloudmusic-plugin-UNM/releases/tag/v1.1.2
