### ISSUE TITLE
docker问题

### ISSUE THREAD

**Issue by btrencai** [FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM#4]
构建了docker版本，使用时开始会显示歌名和封面，但是不到1s立马会变成这样（如图）
![48013f4d97498ff1c320e2f124fcf18](https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM/assets/88539735/44d95064-594c-48ce-ae0a-53698860186e)

**Comment by FiveHair** [comment]
看你在另一个Issues提的log，unm版本不对吧？
是这个吗[v1.1 支持 `!yun stop` 停止播放](https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM/releases/tag/v1.1)

**Comment by btrencai** [comment]
对的

**Comment by FiveHair** [comment]
本项目里的Dockerfile是网友提的arm版的pr，我手头没有arm设备没有测试过。
您可以试试ancieque打包好的[ts3audiobot](https://hub.docker.com/r/ancieque/ts3audiobot)的镜像。

**Comment by btrencai** [comment]
刚刚试了ancieque打包好的的镜像，仍是一样的问题，请问应该怎么在docker中新建机器人呀，我感觉我机器人建的不太对

**Comment by FiveHair** [comment]
> 刚刚试了ancieque打包好的的镜像，仍是一样的问题，请问应该怎么在docker中新建机器人呀，我感觉我机器人建的不太对

...... 您去翻翻[TS3AudioBot](https://github.com/Splamy/TS3AudioBot)吧。
看您截图点歌机的简介是歌曲的url，最新的unm的简介应该是歌曲名称啊

**Comment by btrencai** [comment]
好滴，实在是麻烦了，谢谢您

**Comment by lauren12133** [comment]
> 好滴，实在是麻烦了，谢谢您

我是dockerfile的提供人，dockerfile文件基于主线audiobot提供的项目修改而来。基础运行程序基于主线最新的0.12.0 bot（主要修改了权限运行方式，和加入了yt-dlp支持）此外无任何改动。因此该问题和docker无关。 在https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin中曾经看到有人提播放歌曲头像文件过大导致显示失败，你遇到的是否为同样的情况。

**Comment by btrencai** [comment]
> > 好滴，实在是麻烦了，谢谢您
> 
> 我是dockerfile的提供人，dockerfile文件基于主线audiobot提供的项目修改而来。基础运行程序基于主线最新的0.12.0 bot（主要修改了权限运行方式，和加入了yt-dlp支持）此外无任何改动。因此该问题和docker无关。 在https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin中曾经看到有人提播放歌曲头像文件过大导致显示失败，你遇到的是否为同样的情况。

测试过啦，不是dockerfile的问题，但是这个问题找不到原因😂，网易云api也不再维护了，暂时用用就好了

**Comment by lauren12133** [comment]
> > > 好滴，实在是麻烦了，谢谢您
> > 
> > 
> > 我是dockerfile的提供人，dockerfile文件基于主线audiobot提供的项目修改而来。基础运行程序基于主线最新的0.12.0 bot（主要修改了权限运行方式，和加入了yt-dlp支持）此外无任何改动。因此该问题和docker无关。 在[https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin中曾经看到有人提播放歌曲头像文件过大导致显示失败，你遇到的是否为同样的情况。](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin%E4%B8%AD%E6%9B%BE%E7%BB%8F%E7%9C%8B%E5%88%B0%E6%9C%89%E4%BA%BA%E6%8F%90%E6%92%AD%E6%94%BE%E6%AD%8C%E6%9B%B2%E5%A4%B4%E5%83%8F%E6%96%87%E4%BB%B6%E8%BF%87%E5%A4%A7%E5%AF%BC%E8%87%B4%E6%98%BE%E7%A4%BA%E5%A4%B1%E8%B4%A5%EF%BC%8C%E4%BD%A0%E9%81%87%E5%88%B0%E7%9A%84%E6%98%AF%E5%90%A6%E4%B8%BA%E5%90%8C%E6%A0%B7%E7%9A%84%E6%83%85%E5%86%B5%E3%80%82)
> 
> 测试过啦，不是dockerfile的问题，但是这个问题找不到原因😂，网易云api也不再维护了，暂时用用就好了

你是什么设备 我目前使用的是arm的设备 测试没有你说的问题 唯一一次复现 是在连续执行命令 但是一会儿后就恢复了 建议尝试重启api容器和bot容器

**Comment by lauren12133** [comment]
> > 刚刚试了ancieque打包好的的镜像，仍是一样的问题，请问应该怎么在docker中新建机器人呀，我感觉我机器人建的不太对
> 
> ...... 您去翻翻[TS3AudioBot](https://github.com/Splamy/TS3AudioBot)吧。 看您截图点歌机的简介是歌曲的url，最新的unm的简介应该是歌曲名称啊

pull 此问题源自于网页控制台开启了Show song in bot description 此功能和unm修改简介名字有冲突 需要关闭此功能UNM才可正常接管修改简洁为歌曲名字

**Comment by btrencai** [comment]
> > > 刚刚试了ancieque打包好的的镜像，仍是一样的问题，请问应该怎么在docker中新建机器人呀，我感觉我机器人建的不太对
> > 
> > 
> > ...... 您去翻翻[TS3AudioBot](https://github.com/Splamy/TS3AudioBot)吧。 看您截图点歌机的简介是歌曲的url，最新的unm的简介应该是歌曲名称啊
> 
> pull 此问题源自于网页控制台开启了Show song in bot description 此功能和unm修改简介名字有冲突 需要关闭此功能UNM才可正常接管修改简洁为歌曲名字

感谢您的帮助，问题已解决
