### ISSUE TITLE
机器人无法使用UNM解灰，但是UNM代理是可以使用的，.ini配置的应该也没问题。

### ISSUE THREAD

**Issue by iAmP1us** [FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM#9]
黄字报错是没给机器人权限，与UNM无关。
看了#1，但是我的UNM和API都是docker部署，不知道问题出在哪里

**Comment by ABCDFAS** [comment]
仔细看unm文档 启动参数加了么

**Comment by iAmP1us** [comment]
> 仔细看unm文档 启动参数加了么
unm的参数
docker run  -d -p 8080:8080  -m 300M --memory-swap -1 -e ENABLE_LOCAL_VIP=true -e NO_CACHE=true -e ENABLE_FLAC=true -e NODE_ENV=production --restart=always --log-opt max-size=10m --name=win_music pan93412/unblock-netease-music-enhanced -e https://music.163.com

**Comment by FiveHair** [comment]
在ts里面给机器人权限了吗？可以给个管理员看看还报错不

**Comment by iAmP1us** [comment]
> 在ts里面给机器人权限了吗？可以给个管理员看看还报错不

给了权限，黄字没了，但是UNM还是不行

**Comment by iAmP1us** [comment]
![Uploading QQ截图20240306193849.png…]()

**Comment by iAmP1us** [comment]
![QQ截图20240306193849](https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM/assets/86154051/fac10e15-d350-43b4-bfc8-76b3f3c4f1df)

**Comment by iAmP1us** [comment]
没有任何报错，但是音乐只有45秒的非会员试听版本

**Comment by FiveHair** [comment]
> 没有任何报错，但是音乐只有45秒的非会员试听版本

那你查查UNM吧

**Comment by ABCDFAS** [comment]
端 (1.2 版本以上需要自签证书 MITM，启动客户端需要增加 --ignore-certificate-errors 参数)，

**Comment by iAmP1us** [comment]
> 端 (1.2 版本以上需要自签证书 MITM，启动客户端需要增加 --ignore-certificate-errors 参数)，

这条参数应该是给网易云Linux版客户端用的，

**Comment by wahha2003** [comment]
> 没有任何报错，但是音乐只有45秒的非会员试听版本
如果出现这个情况，说明请求的歌曲在网易云曲库里有，那么插件就会直接带上cookie请求网易云api获取音乐url。如果你登录的网易云账号没有会员，url就是试听的MP3格式，有会员的话就是flac格式的正经歌曲了。

**Comment by wahha2003** [comment]
> 没有任何报错，但是音乐只有45秒的非会员试听版本

如果出现这个情况，说明请求的歌曲在网易云曲库里有，那么插件就会直接带上cookie请求网易云api获取音乐url。如果你登录的网易云账号没有会员，url就是试听的MP3格式，有会员的话就是flac格式的正经歌曲了。也就是说请求不会经过unm。
